spring:
  flyway:
    schemas: HR
    default-schema: HR
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    user: system
    password: hr
    url: jdbc:oracle:thin:@//localhost:1521/orcl
    driver-class-name: oracle.jdbc.OracleDriver
  messages:
    basename: i18n/messages
  application:
    name: backend
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//localhost:1521/orcl
    username: system
    password: hr
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 6060

token:
  secret: 832t82eg8dgwd2fc8cg2bfghbftg8oe8g2e8hihrfghe87drf
  time: 24h
